services:
  mailserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        # DEBIAN_VERSION: "11-slim" # postfix 3.5.6
        DEBIAN_VERSION: "10-slim" # postfix 3.4.14
    image: docker.io/mailserver/docker-mailserver:latest
    # image: docker-mailserver
    container_name: mailserver
    hostname: mail
    domainname: foo.com
    env_file: mailserver.env
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
