blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://docker-mailserver.github.io/docker-mailserver/edge
    about: Extended documentaton - visit this first before opening issues
  - name: Environment Variables Section
    url: https://docker-mailserver.github.io/docker-mailserver/edge/config/environment/
    about: Read this section for information about mail server variables
